In [1]:
import numpy as np

# -----------------------------
# Activation Function
# -----------------------------

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(output):
    # derivative assumes sigmoid output already computed
    return output * (1 - output)

# -----------------------------
# Example Dataset (Replace with yours)
# -----------------------------

inputs = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

outputs = np.array([[0], [1], [1], [0]])

outputs = outputs.reshape(-1, 1)

# -----------------------------
# Network Architecture
# -----------------------------

n_input = inputs.shape[1]
n_hidden1 = 8
n_hidden2 = 6
n_output = 1

# Xavier Initialization for stable gradients
weights0 = np.random.randn(n_input, n_hidden1) * np.sqrt(1 / n_input)
weights1 = np.random.randn(n_hidden1, n_hidden2) * np.sqrt(1 / n_hidden1)
weights2 = np.random.randn(n_hidden2, n_output) * np.sqrt(1 / n_hidden2)

# -----------------------------
# Hyperparameters
# -----------------------------

epochs = 100000
learning_rate = 0.6

# -----------------------------
# Training Loop
# -----------------------------

for epoch in range(1, epochs + 1):

    # =====================
    # Forward Propagation
    # =====================

    input_layer = inputs

    # Layer 1
    z1 = np.dot(input_layer, weights0)
    hidden1 = sigmoid(z1)

    # Layer 2
    z2 = np.dot(hidden1, weights1)
    hidden2 = sigmoid(z2)

    # Output Layer
    z3 = np.dot(hidden2, weights2)
    output_layer = sigmoid(z3)

    # =====================
    # Loss (Mean Absolute Error)
    # =====================

    error_output = outputs - output_layer
    loss = np.mean(np.abs(error_output))

    # =====================
    # Backpropagation
    # =====================

    # ---- Output Layer Gradient ----
    delta_output = error_output * sigmoid_derivative(output_layer)

    # ---- Hidden Layer 2 Gradient ----
    error_hidden2 = delta_output.dot(weights2.T)
    delta_hidden2 = error_hidden2 * sigmoid_derivative(hidden2)

    # ---- Hidden Layer 1 Gradient ----
    error_hidden1 = delta_hidden2.dot(weights1.T)
    delta_hidden1 = error_hidden1 * sigmoid_derivative(hidden1)

    # =====================
    # Weight Updates (Gradient Descent)
    # =====================

    # Update weights2
    weights2 += hidden2.T.dot(delta_output) * learning_rate

    # Update weights1
    weights1 += hidden1.T.dot(delta_hidden2) * learning_rate

    # Update weights0
    weights0 += input_layer.T.dot(delta_hidden1) * learning_rate

    # =====================
    # Accuracy Calculation
    # =====================

    if epoch % 10000 == 0:

        predictions = (output_layer >= 0.5).astype(int)
        correct = np.sum(predictions == outputs)
        total = outputs.shape[0]
        accuracy = correct / total

        print(
            f"Epoch: {epoch} "
            f"Loss: {loss:.15f} "
            f"Accuracy: {accuracy:.15f} "
            f"({correct}/{total})"
        )

# -----------------------------
# Final Results
# -----------------------------

print("\nFinal Probabilities:")
print(output_layer)

print("\nFinal Predictions:")
print((output_layer >= 0.5).astype(int))

Epoch: 10000 Loss: 0.010483873225762 Accuracy: 1.000000000000000 (4/4)
Epoch: 20000 Loss: 0.006847952774853 Accuracy: 1.000000000000000 (4/4)
Epoch: 30000 Loss: 0.005407437481384 Accuracy: 1.000000000000000 (4/4)
Epoch: 40000 Loss: 0.004588572253432 Accuracy: 1.000000000000000 (4/4)
Epoch: 50000 Loss: 0.004045324205119 Accuracy: 1.000000000000000 (4/4)
Epoch: 60000 Loss: 0.003652040560670 Accuracy: 1.000000000000000 (4/4)
Epoch: 70000 Loss: 0.003350797346572 Accuracy: 1.000000000000000 (4/4)
Epoch: 80000 Loss: 0.003110748053185 Accuracy: 1.000000000000000 (4/4)
Epoch: 90000 Loss: 0.002913778797402 Accuracy: 1.000000000000000 (4/4)
Epoch: 100000 Loss: 0.002748470186522 Accuracy: 1.000000000000000 (4/4)

Final Probabilities:
[[0.00241567]
 [0.99709797]
 [0.99721359]
 [0.00288978]]

Final Predictions:
[[0]
 [1]
 [1]
 [0]]


In [2]:
import numpy as np

# -----------------------------
# Activation Functions
# -----------------------------

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(output):
    return output * (1 - output)

# -----------------------------
# Example Dataset (XOR)
# -----------------------------

inputs = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

outputs = np.array([[0], [1], [1], [0]])
outputs = outputs.reshape(-1, 1)

# -----------------------------
# Network Architecture
# -----------------------------

n_input = inputs.shape[1]
n_hidden1 = 8
n_hidden2 = 6
n_output = 1

# He Initialization (important for ReLU)
weights0 = np.random.randn(n_input, n_hidden1) * np.sqrt(2 / n_input)
weights1 = np.random.randn(n_hidden1, n_hidden2) * np.sqrt(2 / n_hidden1)
weights2 = np.random.randn(n_hidden2, n_output) * np.sqrt(2 / n_hidden2)

# -----------------------------
# Hyperparameters
# -----------------------------

epochs = 100000
learning_rate = 0.01   # lower LR recommended for ReLU stability

# -----------------------------
# Training Loop
# -----------------------------

for epoch in range(1, epochs + 1):

    # =====================
    # Forward Propagation
    # =====================

    # Layer 1
    z1 = np.dot(inputs, weights0)
    hidden1 = relu(z1)

    # Layer 2
    z2 = np.dot(hidden1, weights1)
    hidden2 = relu(z2)

    # Output Layer
    z3 = np.dot(hidden2, weights2)
    output_layer = sigmoid(z3)

    # =====================
    # Loss (Mean Absolute Error)
    # =====================

    error_output = output_layer - outputs
    loss = np.mean(np.abs(error_output))

    # =====================
    # Backpropagation
    # =====================

    # Output layer gradient
    delta_output = error_output * sigmoid_derivative(output_layer)

    # Hidden layer 2 gradient
    delta_hidden2 = delta_output.dot(weights2.T) * relu_derivative(z2)

    # Hidden layer 1 gradient
    delta_hidden1 = delta_hidden2.dot(weights1.T) * relu_derivative(z1)

    # =====================
    # Weight Updates (Gradient Descent)
    # =====================

    weights2 -= hidden2.T.dot(delta_output) * learning_rate
    weights1 -= hidden1.T.dot(delta_hidden2) * learning_rate
    weights0 -= inputs.T.dot(delta_hidden1) * learning_rate

    # =====================
    # Accuracy Calculation
    # =====================

    if epoch % 10000 == 0:

        predictions = (output_layer >= 0.5).astype(int)
        correct = np.sum(predictions == outputs)
        total = outputs.shape[0]
        accuracy = correct / total

        print(
            f"Epoch: {epoch} "
            f"Loss: {loss:.15f} "
            f"Accuracy: {accuracy:.15f} "
            f"({correct}/{total})"
        )

# -----------------------------
# Final Results
# -----------------------------

print("\nFinal Probabilities:")
print(output_layer)

print("\nFinal Predictions:")
print((output_layer >= 0.5).astype(int))

Epoch: 10000 Loss: 0.259119606241875 Accuracy: 0.500000000000000 (2/4)
Epoch: 20000 Loss: 0.255986947866281 Accuracy: 0.500000000000000 (2/4)
Epoch: 30000 Loss: 0.254657827319623 Accuracy: 0.500000000000000 (2/4)
Epoch: 40000 Loss: 0.253954725954661 Accuracy: 0.500000000000000 (2/4)
Epoch: 50000 Loss: 0.253453170958363 Accuracy: 0.500000000000000 (2/4)
Epoch: 60000 Loss: 0.253132243570726 Accuracy: 0.500000000000000 (2/4)
Epoch: 70000 Loss: 0.252885419216156 Accuracy: 0.500000000000000 (2/4)
Epoch: 80000 Loss: 0.252639266916922 Accuracy: 0.500000000000000 (2/4)
Epoch: 90000 Loss: 0.252477910370959 Accuracy: 0.500000000000000 (2/4)
Epoch: 100000 Loss: 0.252325339338026 Accuracy: 0.500000000000000 (2/4)

Final Probabilities:
[[0.5       ]
 [0.99540931]
 [0.99528933]
 [0.5       ]]

Final Predictions:
[[1]
 [1]
 [1]
 [1]]
