# Libraries for Neural Networks - sklearn 2 (regression)


## Loading the data

https://www.cs.toronto.edu/~delve/data/boston/bostonDetail.html

In [ ]:
from sklearn.neural_network import MLPRegressor
from sklearn import datasets

In [ ]:
boston = datasets.load_boston()

In [ ]:
inputs = boston.data
inputs

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [ ]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [ ]:
outputs = boston.target
outputs

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [ ]:
boston.target_names

AttributeError: ignored

In [ ]:
inputs.shape

(506, 13)

In [ ]:
outputs.shape

(506,)

## Train and test datasets

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, outputs, test_size = 0.2)

In [ ]:
X_train.shape

(404, 13)

In [ ]:
y_train.shape

(404,)

In [ ]:
X_test.shape

(102, 13)

In [ ]:
y_test.shape

(102,)

In [ ]:
max(X_train[0])

387.38

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler1 = MinMaxScaler()
X_train = scaler1.fit_transform(X_train)
X_test = scaler1.transform(X_test)

In [ ]:
max(X_train[0])

0.9759947551565888

In [ ]:
y_train = y_train.reshape(-1, 1)
y_test = y_test.reshape(-1, 1)

In [ ]:
y_train.shape

(404, 1)

In [ ]:
scaler2 = MinMaxScaler()
y_train = scaler2.fit_transform(y_train)
y_test = scaler2.transform(y_test)

In [ ]:
max(y_train[0])

0.7244444444444444

## Neural network (training)

In [ ]:
(13 + 1) / 2

7.0

In [ ]:
network = MLPRegressor(max_iter=2000, verbose=True, hidden_layer_sizes=(7))
network.fit(X_train, y_train)

Iteration 1, loss = 0.13175798
Iteration 2, loss = 0.11679720
Iteration 3, loss = 0.10321247
Iteration 4, loss = 0.09148107
Iteration 5, loss = 0.08139271
Iteration 6, loss = 0.07284470
Iteration 7, loss = 0.06545187
Iteration 8, loss = 0.05909055
Iteration 9, loss = 0.05364205
Iteration 10, loss = 0.04917420
Iteration 11, loss = 0.04554622
Iteration 12, loss = 0.04259327
Iteration 13, loss = 0.04017788
Iteration 14, loss = 0.03829202
Iteration 15, loss = 0.03680972
Iteration 16, loss = 0.03573031
Iteration 17, loss = 0.03483737
Iteration 18, loss = 0.03409210
Iteration 19, loss = 0.03342929
Iteration 20, loss = 0.03280812
Iteration 21, loss = 0.03221890
Iteration 22, loss = 0.03166174
Iteration 23, loss = 0.03114186
Iteration 24, loss = 0.03064682
Iteration 25, loss = 0.03013514
Iteration 26, loss = 0.02961449
Iteration 27, loss = 0.02909473
Iteration 28, loss = 0.02863613
Iteration 29, loss = 0.02820861
Iteration 30, loss = 0.02779571
Iteration 31, loss = 0.02736619
Iteration 32, los

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1342: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=7, learning_rate='constant',
             learning_rate_init=0.001, max_fun=15000, max_iter=2000,
             momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
             power_t=0.5, random_state=None, shuffle=True, solver='adam',
             tol=0.0001, validation_fraction=0.1, verbose=True,
             warm_start=False)

In [ ]:
network.coefs_

[array([[-1.70001398e-02, -1.07363916e-01, -6.41480557e-02, ...,
         -1.97038057e-02,  5.37078534e-02,  5.84918200e-02],
        [ 5.23436137e-02,  1.75236791e-01, -1.55627221e-02, ...,
         -2.06495207e-02, -7.48453160e-02,  9.59534278e-02],
        [-1.53727241e-02,  1.30440587e-01, -2.19080324e-02, ...,
         -2.33758050e-02,  2.98612833e-02, -6.77335334e-03],
        ...,
        [ 1.27068416e-01,  8.94074756e-02, -1.75862155e-01, ...,
          3.30844879e-04, -9.87053095e-02,  4.02285919e-02],
        [ 1.38548976e-01,  2.47316566e-01, -2.07070615e-01, ...,
         -4.37187941e-08,  1.72163953e-01,  8.41217515e-02],
        [ 1.48828234e-01,  6.65439719e-02,  1.02879872e-02, ...,
         -5.94107719e-03,  2.53755543e-02,  6.81014194e-02]]),
 array([[-4.63554421e-02],
        [ 9.58733422e-02],
        [-1.38812366e-01],
        [ 1.05412485e-01],
        [ 2.34566489e-01],
        [ 1.55807991e-01],
        [-1.16543505e-01],
        [-1.88850597e-01],
        [ 1.2

In [ ]:
network.intercepts_

[array([-0.16219769,  0.18182999,  0.153054  , -0.14619065, -0.02856149,
         0.1548824 ,  0.19914878,  0.03785903,  0.03235847, -0.0528781 ,
        -0.20174511,  0.11246161, -0.00505192,  0.04670787,  0.14931424,
        -0.13853806,  0.03166341, -0.06003787, -0.04225912,  0.19515933,
         0.04183626,  0.22483178,  0.03171703, -0.18509336, -0.04868291,
        -0.01842088, -0.11189007,  0.16391857,  0.06550444,  0.03943483,
         0.04433274,  0.14003143, -0.03450163, -0.09613382,  0.02194552,
         0.14002467,  0.08238234,  0.00298872,  0.07621368,  0.08108414,
         0.0762791 , -0.08855925, -0.21006047,  0.24356275, -0.22568248,
         0.03898561, -0.00305392,  0.08741928, -0.1813166 , -0.18388083,
         0.18531852, -0.10623291, -0.02632494, -0.10674098, -0.07112031,
         0.19075328, -0.07159242, -0.1197932 ,  0.11380981,  0.06025515,
        -0.01910202,  0.00867749, -0.12567995, -0.10464992,  0.11589837,
        -0.17106342,  0.04806824,  0.179107  ,  0.1

In [ ]:
network.n_layers_

3

In [ ]:
network.n_outputs_

1

In [ ]:
network.out_activation_

'identity'

## Neural network (evaluation)

In [ ]:
X_test.shape

(102, 13)

In [ ]:
predictions = network.predict(X_test)
predictions

array([ 2.24385248e-01,  4.74919501e-01,  2.57352444e-01,  2.35949537e-01,
        4.92267530e-01,  3.04969428e-01,  3.14736747e-01,  3.03623610e-01,
        6.35170662e-01,  3.76468771e-01,  1.95392767e-01,  1.73807830e-01,
        3.99175894e-01,  8.58599456e-02,  4.68995767e-01,  1.31766823e-01,
        3.63673385e-01,  5.02450365e-01,  4.21477525e-01,  5.50860879e-01,
        4.58478913e-01,  4.96043606e-01,  2.79953605e-01,  2.79260459e-01,
        6.29888287e-02,  4.58894444e-01,  2.68414857e-01,  4.90694176e-01,
        4.76198282e-01,  2.71268197e-01,  3.44147594e-01,  6.23060055e-01,
        4.13297706e-01,  1.41730037e-01,  1.20539109e-01,  4.62583554e-01,
        6.20345074e-01,  5.46363952e-01,  3.93320446e-01,  3.24862227e-01,
        4.19342838e-01,  4.49693771e-01,  1.71178942e-01,  3.13335733e-01,
        4.63534958e-01,  2.86915916e-01,  5.11877415e-01,  2.68226046e-01,
        1.54071187e-01,  1.03394089e-01,  1.24827400e-01,  5.71042798e-01,
       -5.95719357e-05,  

In [ ]:
y_test

array([[0.14      ],
       [0.34444444],
       [0.44444444],
       [0.31111111],
       [0.19111111],
       [0.20222222],
       [0.12      ],
       [0.37777778],
       [0.36666667],
       [0.40444444],
       [0.30666667],
       [0.04888889],
       [0.31777778],
       [0.21111111],
       [0.66      ],
       [0.33111111],
       [0.30444444],
       [0.44666667],
       [0.28      ],
       [0.28444444],
       [0.71777778],
       [0.53555556],
       [0.19555556],
       [0.38222222],
       [0.08444444],
       [0.37777778],
       [0.18888889],
       [0.37777778],
       [0.3       ],
       [0.25333333],
       [0.47111111],
       [0.80666667],
       [0.04444444],
       [0.39555556],
       [0.27111111],
       [0.41777778],
       [0.82888889],
       [0.41777778],
       [0.34222222],
       [0.44444444],
       [0.24444444],
       [0.40444444],
       [0.42444444],
       [0.32666667],
       [0.67555556],
       [0.18444444],
       [0.18      ],
       [0.304

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
mean_absolute_error(y_test, predictions)

0.14060813362789104

In [ ]:
mean_squared_error(y_test, predictions)

0.03178806458916762

In [ ]:
import numpy as np
np.sqrt(mean_squared_error(y_test, predictions))

0.1782920766303641

## Neural network (classification)

In [ ]:
X_test[0], y_test[0]

(array([0.12486029, 0.        , 0.64662757, 0.        , 0.64814815,
        0.37842499, 1.        , 0.04705293, 1.        , 0.91395793,
        0.80851064, 1.        , 0.60347682]), array([0.14]))

In [ ]:
X_test[0].shape

(13,)

In [ ]:
new = X_test[0].reshape(1, -1)
new.shape

(1, 13)

In [ ]:
network.predict(new)

array([0.22438525])

In [ ]:
scaler2.inverse_transform(network.predict(new).reshape(-1,1))

array([[15.09733614]])

In [ ]:
scaler2.inverse_transform(y_test[0].reshape(-1,1))

array([[11.3]])